### ISSUE TITLE
storybook:web not working properly

### ISSUE THREAD

**Issue by narin** [mauro-codes/expo-router-storybook-starter#1]
Appreciate the tutorial! I cloned the repo and am getting a "Couldn't find any stories in your Storybook." error when running `npm run storybook:web`.  Any idea what might be going on? Strangely, it works fine if I do `npm run start` and choose the web option.

<img width="1284" alt="image" src="https://github.com/mauro-codes/expo-router-storybook-starter/assets/786704/25bce7d1-447e-47b9-9b39-e09b885862c2">

**Comment by narin** [comment]
Never mind, I figured it out! `main.js` is configured to look for stories in the components dir, but this repo structure has them in the `.storybook/stories`. Need to either move the stories or update `main.js`.

**Comment by mauro-codes** [comment]
My bad! Thanks for letting me know. Already fixed it
